Repository Azure/azure-devops-cli-extension, pull requests merged in 2019-01, with the labels that each got.

#344 fail in case some style check fails
  scripts/runStyleCheck.ps1
Labels: bug

#348 use resource name instead of Id in param when it can take both name a…
  azure-devops/azext_devops/dev/admin/arguments.py
  azure-devops/azext_devops/dev/admin/banner.py
  azure-devops/azext_devops/dev/boards/arguments.py
  azure-devops/azext_devops/dev/boards/work_item.py
  azure-devops/azext_devops/dev/pipelines/arguments.py
  azure-devops/azext_devops/dev/pipelines/build.py
  azure-devops/azext_devops/dev/pipelines/build_definition.py
  azure-devops/azext_devops/dev/pipelines/release.py
  azure-devops/azext_devops/dev/pipelines/release_definition.py
  azure-devops/azext_devops/dev/pipelines/task.py
  azure-devops/azext_devops/dev/repos/arguments.py
  azure-devops/azext_devops/dev/repos/pull_request.py
  azure-devops/azext_devops/dev/repos/repository.py
  azure-devops/azext_devops/dev/team/project.py
  azure-devops/azext_devops/dev/team/team.py
  azure-devops/azext_devops/test/boards/test_workitem.py
  azure-devops/azext_devops/test/pipelines/test_pipelines_build.py
  azure-devops/azext_devops/test/repos/test_pull_request.py
  azure-devops/azext_devops/test/repos/test_repository.py
  tests/devopsProjectTest.py
  tests/devopsTeamTest.py
  tests/pipelinesBuildDefinitionsTest.py
  tests/pipelinesBuildTaskTest.py
  tests/pipelinesBuildTest.py
  tests/reposRepoTest.py
Labels: Task

#347 use test_ so that pytest can discover recorded test files as test files
  scripts/runTests.ps1
  tests/test_adminBannerTest.py
  tests/test_boardsQueryTest.py
  tests/test_boardsWorkItemTest.py
  tests/test_devopsProjectTest.py
  tests/test_devopsTeamTest.py
  tests/test_pipelinesBuildDefinitionsTest.py
  tests/test_pipelinesBuildTaskTest.py
  tests/test_pipelinesBuildTest.py
  tests/test_reposImportTest.py
  tests/test_reposPrCommandsReviewersTest.py
  tests/test_reposPrPoliciesWorkItemsTest.py
  tests/test_reposRepoTest.py
Labels: Infra, enhancement

#376 changes to upgrade pip and not install keyring while preparing machine
  scripts/setupCiMachine.ps1
Labels: Task

#396 Setup live test run pipeline
  .azure-pipelines/azure-pipelines-live-test-run.yml
  azure-devops/azext_devops/test/__init__.py
  azure-devops/azext_devops/test/artifacts/test_univeral.py
  azure-devops/azext_devops/test/boards/test_workitem.py
  azure-devops/azext_devops/test/repos/test_pull_request.py
  azure-devops/azext_devops/test/repos/test_repository.py
  azure-devops/azext_devops/test/team/test_service_endpoint.py
  azure-devops/azext_devops/test/utils/__init__.py
  azure-devops/azext_devops/test/utils/helper.py
  scripts/prepareLiveRecordingTestsRun.py
  scripts/runTests.ps1
  tests/recordings/test_admin_banner_addUpdateShowListRemove.yaml
  tests/recordings/test_build_definition_listShow.yaml
  tests/recordings/test_build_listQueueShow.yaml
  tests/recordings/test_build_task_listShow.yaml
  tests/recordings/test_devops_projects_CreateListShowDelete.yaml
  tests/recordings/test_devops_repos_policies_createUpdateShowListDelete.yaml
  tests/recordings/test_devops_team_createUpdateShowListDeleteListMember.yaml
  tests/recordings/test_pull_request_createUpdateVoteListAbandonReactivateCompleteReviewers.yaml
  tests/recordings/test_pull_request_policies_workitems.yaml
  tests/recordings/test_queryShow.yaml
  tests/recordings/test_repos_createListShowDelete.yaml
  tests/recordings/test_repos_import_create.yaml
  tests/recordings/test_workItemCreateShowUpdateDelete.yaml
  tests/test_adminBannerTest.py
  tests/test_boardsQueryTest.py
  tests/test_boardsWorkItemTest.py
  tests/test_devopsProjectTest.py
  tests/test_devopsTeamTest.py
  tests/test_pipelinesBuildDefinitionsTest.py
  tests/test_pipelinesBuildTaskTest.py
  tests/test_pipelinesBuildTest.py
  tests/test_reposImportTest.py
  tests/test_reposPoliciesTest.py
  tests/test_reposPrCommandsReviewersTest.py
  tests/test_reposPrPoliciesWorkItemsTest.py
  tests/test_reposRepoTest.py
  tests/utilities/helper.py
Labels: Infra

#399 Allow recording tests to run on any organization
  doc/authoring_tests.md
  tests/recordings/test_devops_repos_policies_createUpdateShowListDelete.yaml
  tests/recordings/test_repos_policies_createUpdateShowListDelete.yaml
  tests/test_adminBannerTest.py
  tests/test_boardsQueryTest.py
  tests/test_boardsWorkItemTest.py
  tests/test_devopsProjectTest.py
  tests/test_devopsTeamTest.py
  tests/test_pipelinesBuildDefinitionsTest.py
  tests/test_pipelinesBuildTaskTest.py
  tests/test_pipelinesBuildTest.py
  tests/test_reposImportTest.py
  tests/test_reposPoliciesTest.py
  tests/test_reposPrCommandsReviewersTest.py
  tests/test_reposPrPoliciesWorkItemsTest.py
  tests/test_reposRepoTest.py
  tests/utilities/helper.py
Labels: Infra
